# Generated by Django 3.1.7 on 2021-04-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210402_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
    ]
