# Generated by Django 3.1.7 on 2021-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210403_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionvideo',
            name='path',
            field=models.CharField(default='default', max_length=1000),
        ),
    ]
