# Generated by Django 3.1.7 on 2021-05-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210528_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionvideo',
            name='path',
            field=models.CharField(default=models.CharField(default='default', max_length=100), max_length=1000),
        ),
    ]
