# Generated by Django 3.1.7 on 2021-05-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210527_2022'),
        ('app', '0014_auto_20210528_0007'),
    ]

    operations = [
    ]
