# Generated by Django 3.1.7 on 2021-05-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20210529_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150, unique=True)),
                ('carno', models.CharField(max_length=50, unique=True)),
                ('carmodel', models.CharField(max_length=50)),
                ('carcolour', models.CharField(max_length=50)),
            ],
        ),
    ]
