# Generated by Django 3.1.7 on 2021-05-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210529_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofile',
            name='carno',
            field=models.CharField(max_length=50),
        ),
    ]
