# Generated by Django 3.1.7 on 2021-05-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210529_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprofile',
            name='phone',
            field=models.CharField(max_length=150),
        ),
    ]
