# Generated by Django 3.1.7 on 2021-05-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_detectionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
